### ISSUE TITLE
Where statement not case sensitive

### ISSUE THREAD

**Issue by daika7ana** [devpri/tinre-core#2]
https://github.com/devpri/tinre-core/blob/767fc8ebbe86442f0a647d668fb3f0f1dcc32e85/src/Http/Controllers/RedirectController.php#L14

Just so you know, Laravel where statement is not case sensitive. Your 'path' column in the migration is also not '_bin' collation therefore you can get bad redirects. 
Example: 
https://tin.re/fVuffe ( goes to youtube ) -> this is the link your platform generated
https://tin.re/fVuffE ( also goes to youtube ) -> this should give me a 404 since it's not the link I generated

Solution:
Either apply `->collation('utf8_bin')` to the path column in the collation to make the where always case sensitive when looking on this column or change this where statement to something like:
``Url::whereRaw("BINARY `path`= ?",[$path])->where( 'active' => 1)->first(); ``
to make only this where statement case sensitive.

**Comment by paulprisacaru** [comment]
Thanks! I prefer the URLs to be case insensitive.

**Comment by daika7ana** [comment]
Alrighty! If it's intended, then my bad for assuming otherwise. 
Usually, the URL shorteners that I've seen use case sensitive approach in order to allow for more 'path' or 'key' combinations to fully take advantage of all the 62 characters (a-zA-Z0-9) available (5.6E10 combinations). 

However, this being said, I also get you why you'd maybe want to make them case insensitive - most likely to avoid human error. We're already talking about some absurd numbers of URLs generated ( 2.1E9 combinations ) before reaching a brick wall and having to either increase the number of characters, or the number of tries for the recursive part where you look for an empty path. (Noticed that you use a 6 char path, and 5 passes to look for an empty path)

**Comment by paulprisacaru** [comment]
You are right. I want to avoid human error, especially for custom paths.
