### ISSUE TITLE
Module not found: Error: Can't resolve '../pages/users/index

### ISSUE THREAD

**Issue by GovarJabbar** [devpri/tinre-core#4]
please capitalize that two vue file names:
https://github.com/devpri/tinre-core/blob/a5654d73a0d313843c72e487e43a9afb0efd99ab/resources/js/router/routes.js#L4
to `import UsersIndex from '../pages/users/Index'
`

https://github.com/devpri/tinre-core/blob/a5654d73a0d313843c72e487e43a9afb0efd99ab/resources/js/router/routes.js#L5
 to `import UsersIndex from '../pages/users/Show'
`
it show error in some npm version.

`ERROR in ./resources/js/router/routes.js
Module not found: Error: Can't resolve '../pages/users/index' in '/var/www/vhosts/rwangroup.com/new/vendor/devpri/tinre-core/resources/js/router'
 @ ./resources/js/router/routes.js 4:0-46 18:13-23
 @ ./resources/js/router/index.js
 @ ./resources/js/dashboard.js
 @ multi ./resources/js/dashboard.js
`

**Comment by paulprisacaru** [comment]
Fixed in 813c8bb119294398f5bfd743581ebd221ba750bd.
