### ISSUE TITLE
change and make all static strings to dynamic

### ISSUE THREAD

**Issue by GovarJabbar** [devpri/tinre-core#5]
some of your strings not dynamic please make it dynamic because now i'm using your packege and i make it multi language but there are few lines:
https://github.com/devpri/tinre-core/blob/a5654d73a0d313843c72e487e43a9afb0efd99ab/resources/js/components/url/Create.vue#L14
https://github.com/devpri/tinre-core/blob/a5654d73a0d313843c72e487e43a9afb0efd99ab/resources/js/components/url/CreateGuest.vue#L12

**Comment by paulprisacaru** [comment]
Fixed in 5d3edb3041378e856782845585d8669203343734.
